sudo: required
services:
  - docker

before_install:
  - docker build -f dev.Dockerfile -t ruanmoolman/docker-tutorial .

script:
  - docker run -e CI=true ruanmoolman/docker-tutorial npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "eu-west-2"
  app: "simplefe"
  env: "Simplefe-env"
  bucket_name: "elasticbeanstalk-eu-west-2-229431878733"
  bucket_path: "simplefe"
  on:
    branch: "master"
